version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.8
    commands:
      - "cd /usr/bin"
      - echo $TF_VERSION
      - echo $SRC_DIR
      - "curl -s -qL -o terraform.zip https://releases.hashicorp.com/terraform/${TF_VERSION}/terraform_${TF_VERSION}_linux_amd64.zip"
      - "unzip -o terraform.zip"

  build:
    commands:
        - cd $CODEBUILD_SRC_DIR
        - chmod u+x build_plan.sh
        - ./build_plan.sh
        - if [ $? -ne 0 ]; then exit 1; fi


  post_build:
    commands:
      - echo "Terraform plan completed on `date`"

artifacts:
  files:
    - '**/*'
