version: 0.2
phases:
  install:
    runtime-versions:
      python: 3.8
    commands:
      - echo "Installing dependencies...but no dependencies"
  build:
    commands:
      - echo "Zipping deployment package...but nothing to zip"
#       - cd lib
#       - zip -r9 ../deployment_package.zip .
#       - cd ..
      - zip -g deployment_package.zip lambda_function.py
  post_build:
    commands:
      - echo "Updating lambda Function..."
      - aws lambda update-function-code --function-name test-lambda --zip-file fileb://deployment_package.zip
      - echo "DONE!!"
